name: 🚧 Request for Comments (RFC)
description: Feature design and detailed proposals
title: "RFC: TITLE"
labels: ["RFC-proposal", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a RFC. Please add as many details as possible to help further enrich this design.
  - type: input
    id: relation
    attributes:
      label: Is this related to an existing feature request or issue?
      description: Please share a link, if applicable
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Please provide an overview in one or two paragraphs
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Use case
      description: Please share the use case and motivation behind this proposal
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Please explain the design in detail, so anyone familiar with the project could implement it
      placeholder: What the user experience looks like before and after this design?
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Out of scope
      description: Please explain what should be considered out of scope in your proposal
    validations:
      required: true
  - type: textarea
    id: challenges
    attributes:
      label: Potential challenges
      description: Nothing is perfect. Please share what common challenges, edge cases, unresolved areas, and suggestions on how to mitigate them
    validations:
      required: true
  - type: textarea
    id: integrations
    attributes:
      label: Dependencies and Integrations
      description: If applicable, please share whether this feature has additional dependencies, and how it might integrate with other utilities available
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative solutions
      description: Please describe what alternative solutions to this use case, if any
      render: markdown
    validations:
      required: false
  - type: checkboxes
    id: acknowledgment
    attributes:
      label: Acknowledgment
      options:
        - label: This RFC proposal meets [GenAI CDK constructs design guidelines](https://github.com/awslabs/generative-ai-cdk-constructs/blob/main/DESIGN_GUIDELINES.md)
          required: true
  - type: markdown
    attributes:
      value: |
        ---

        **Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

        Metadata information for admin purposes, please leave them empty.

        * RFC PR:
        * Approved by: ''
        * Reviewed by: ''
