name: 💞 Support Generative AI CDK constructs (become a reference)
description: Add your organization's name or logo to the Generative AI CDK constructs documentation
title: "[Support Generative AI CDK constructs]: <your organization name>"
labels: ["customer-reference"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for becoming a reference customer. Your support means a lot to us. It also helps new customers to know who's using it.

        If you would like us to also display your organization's logo, please share a link in the `Company logo` field.
  - type: input
    id: organization
    attributes:
      label: Organization Name
      description: Please share the name of your organization
      placeholder: ACME
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Your Name
      description: Please share your name
    validations:
      required: true
  - type: input
    id: job
    attributes:
      label: Your current position
      description: Please share your current position at your company
    validations:
      required: true
  - type: input
    id: logo
    attributes:
      label: (Optional) Company logo
      description: Company logo you want us to display. You also allow us to resize for optimal placement in the documentation.
    validations:
      required: false
  - type: textarea
    id: use_case
    attributes:
      label: (Optional) Use case
      description: How are you using Generative AI CDK constructs today? *features, etc.*
    validations:
      required: false
  - type: checkboxes
    id: languages
    attributes:
      label: What languages are you using for Generative AI CDK constructs?
      options:
        - label: Java
          required: false
        - label: Go
          required: false
        - label: TypeScript
          required: false
        - label: .NET
          required: false
        - label: Python
          required: false
  - type: markdown
    attributes:
      value: |
        *By raising a Support Generative AI CDK constructs issue, you are granting AWS permission to use your company's name (and/or logo) for the limited purpose described here. You are also confirming that you have authority to grant such permission.*

        *You can opt-out at any time by commenting or reopening this issue.*
